//Регистрация пользователя
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

//Авторизация пользователя на сайте
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

//Выход пользователя с сайта
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILED = "USER_LOGOUT_FAILED";

//Отправка email на сброс пароля
export const FORGOUT_PASSWORD_REQUEST = "FORGOUT_PASSWORD_REQUEST";
export const FORGOUT_PASSWORD_SUCCESS = "FORGOUT_PASSWORD_SUCCESS";
export const FORGOUT_PASSWORD_FAILED = "FORGOUT_PASSWORD_FAILED";

//Отправка нового пароля и токена
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

//Отправка данных пользователя

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

//Получение данных о пользователе
export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_FAILED = "USER_INFO_FAILED";

//Обновление токена
export const TOKEN_UPDATE_REQUEST = "TOKEN_UPDATE_REQUEST";
export const TOKEN_UPDATE_SUCCESS = "TOKEN_UPDATE_SUCCESS";
export const TOKEN_UPDATE_FAILED = "TOKEN_UPDATE_FAILED";
